import type { BaseLayoutProps } from "fumadocs-ui/layouts/shared"
import { appName, githubUrl } from "./shared"

export function baseOptions(): BaseLayoutProps {
  return {
    nav: {
      title: (
        <>
          {/* Theme-aware goose mark (generated by scripts/generate-logos.mjs) */}
          {/* biome-ignore lint/a11y/useAltText: decorative, name is adjacent */}
          <img src="/logo-light.png" alt="" width={36} height={36} className="nav-logo dark:hidden" />
          {/* biome-ignore lint/a11y/useAltText: decorative, name is adjacent */}
          <img src="/logo-dark.png" alt="" width={36} height={36} className="nav-logo hidden dark:block" />
          <span style={{ fontWeight: 700 }}>{appName}</span>
        </>
      ),
    },
    githubUrl,
  }
}
